apiVersion: v1
kind: Service
metadata:
  name: livekit
  namespace: meeting-platform
spec:
  selector:
    app: livekit
  ports:
  - name: ws
    port: 7880
    targetPort: 7880
  - name: http
    port: 7881
    targetPort: 7881
  - name: rtp
    port: 50000
    targetPort: 50000
    protocol: UDP
  type: ClusterIP

